version: '3.9'
services:
  web_comic:
    env_file:
      - .env
    container_name: ${WEB_HOST}
    hostname: ${WEB_HOST}
    build: ./app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      FLASK_RUN_HOST: 0.0.0.0
      TEMPLATES_AUTO_RELOAD: 'True'
      FLASK_ENV: development
    ports: 
      - '8001:5000'
    volumes:
      - ./app:/app
    networks:
      - coppel
volumes:
  persistent:
networks:
  coppel:
    driver: bridge